package com.iso2t.easyconfig.api.annotations;

import com.iso2t.easyconfig.api.value.comment.AutoCommentValueProvider;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * An annotation to attach comments to configuration elements for use in serialized outputs.
 * The comments can include static text, dynamic values generated by a custom provider,
 * or both.
 * <p>
 * The serialized comments will appear above the annotated field or type in the
 * generated configuration files.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target( { ElementType.TYPE, ElementType.FIELD })
public @interface Comment {
	/**
	 * Specifies the comment lines to be associated with the annotated config element.
	 * These comment lines will be emitted above the configuration field or type when serialized.
	 *
	 * @return an array of strings representing the comment lines. If no value is specified, an empty array is returned.
	 */
	String[] value () default {};

	/**
	 * Determines whether the annotated configuration element should include
	 * a dynamic comment generated from its value.
	 * <p>
	 * When set to {@code true}, the {@link CommentValueProvider} specified by
	 * {@link #provider()} will be used to provide the comment lines.
	 *
	 * @return {@code true} if dynamic comments based on the value are enabled;
	 *         {@code false} otherwise.
	 */
	boolean values () default true;

	/**
	 * Specifies the class of the {@link CommentValueProvider} to be used
	 * for generating dynamic comment lines for an annotated configuration element.
	 * <p>
	 * When set to {@code AutoCommentValueProvider.class}, the system attempts
	 * to automatically determine an appropriate {@link CommentValueProvider}
	 * based on the type of the annotated field or configuration element.
	 *
	 * @return the class of the {@link CommentValueProvider} to use,
	 *         or {@code AutoCommentValueProvider.class} if the provider should
	 *         be determined automatically.
	 */
	Class<? extends CommentValueProvider<?>> provider () default AutoCommentValueProvider.class;
}
